// examples/basic-app/src/Layout.vue
<template>
  <div>
    <nav>
      <Link 
        v-for="item in menu" 
        :key="item.href" 
        :href="item.href" 
        style="margin-right: 12px"
      >
        {{ item.label }}
      </Link>
    </nav>
    <div v-if="flash.success" style="background: #d4edda; color: #155724; padding: 10px; margin-bottom: 20px;">
      {{ flash.success }}
    </div>
    <div v-if="flash.error" style="background: #f8d7da; color: #721c24; padding: 10px; margin-bottom: 20px;">
      {{ flash.error }}
    </div>
    <main>
      <slot />
    </main>
  </div>
</template>

<script setup>
import { Link, usePage } from '@inertiajs/vue3'
import { computed } from 'vue'

const page = usePage()
const menu = computed(() => page.props.menu)
const flash = computed(() => page.props.flash || {})
</script>

// examples/basic-app-react/src/Layout.jsx
import { Link, usePage } from '@inertiajs/react'

export default function Layout({ children }) {
  const page = usePage()
  const menu = page.props.menu ?? []
  const flash = page.props.flash ?? {}

  return (
    <div className="app-container">
      <nav>
        {menu.map((item) => (
          <Link
            key={item.href}
            href={item.href}
            className={page.url === item.href ? 'active' : undefined}
          >
            {item.label}
          </Link>
        ))}
      </nav>

      {flash.success && <div className="flash flash-success">{flash.success}</div>}
      {flash.error && <div className="flash flash-error">{flash.error}</div>}

      <main className="card">{children}</main>
    </div>
  )
}
